services:
  backend:
    build: .
    container_name: WalletAPI
    ports:
      - "8000:80"
    volumes:
      - ".:/var/www/html"
    networks:
      - WalletAPI_network 
    depends_on:
      - db 
  db:
    image: postgres:16
    container_name: WalletAPI_db
    environment:
      POSTGRES_DB: WalletAPI
      POSTGRES_USER: user
      POSTGRES_PASSWORD: root123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data  
    networks:
      - WalletAPI_network       

volumes:
  pgdata:

networks:
  WalletAPI_network:
    driver: bridge

