user nginx;
worker_processes auto;

events { worker_connections 1024; }

http {
    server {
        listen 80;
        server_name localhost;

        root /var/www/html/WalletAPI/public;
        index index.php index.html index.htm;

        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS';
        add_header 'Access-Control-Allow-Headers' 'Origin, Content-Type, X-Requested-With, Accept, Authorization';
        add_header 'Access-Control-Allow-Credentials' 'true';

        if ($request_method = 'OPTIONS') {
            return 204;
        }

        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }

        location ~ \.php$ {
            include fastcgi_params;
            fastcgi_pass backend:9000;  # PHP-FPM
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME /var/www/html/WalletAPI/public$fastcgi_script_name;

            add_header 'Access-Control-Allow-Origin' '*';
            add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS';
            add_header 'Access-Control-Allow-Headers' 'Origin, Content-Type, X-Requested-With, Accept, Authorization';
            add_header 'Access-Control-Allow-Credentials' 'true';
        }

        location ~ /\.ht {
            deny all;
        }
    }
}
